CREATE TABLE "YDZC"."UOS_STAFF_IOM" 
   (	"STAFF_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STAFF_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"STAFF_CODE" VARCHAR2(64), 
	"STAFF_ALIAS" VARCHAR2(40), 
	"USERNAME" VARCHAR2(64) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(64) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(60), 
	"HOME_TEL" VARCHAR2(20), 
	"OFFICE_TEL" VARCHAR2(20), 
	"MOBILE_TEL" VARCHAR2(64), 
	"ADDRESS1" VARCHAR2(254), 
	"ADDRESS2" VARCHAR2(254), 
	"AGENT" NUMBER(8,0), 
	"VALID_COMM_MODE" CHAR(2) DEFAULT 2 NOT NULL ENABLE, 
	"DEPARTMENT" VARCHAR2(40), 
	"STATE" CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	"DELETE_STATE" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"EFFECT_DATE" DATE NOT NULL ENABLE, 
	"EXPIRE_DATE" DATE, 
	"UPDATE_DATE" DATE, 
	"DELETE_TIME" DATE, 
	"COMMENTS" VARCHAR2(1024), 
	"DEFAULT_SERVICE_ABILITY_ID" NUMBER(3,0), 
	"CONSTRUCT_ABILITY" NUMBER(3,0), 
	"SERVER_GRADE" NUMBER(3,0), 
	"NATION_ID" NUMBER(3,0) DEFAULT 1, 
	"FAULT_COMPLET" NUMBER(8,5), 
	"ISPARTER" VARCHAR2(3), 
	"WORK_STATE" VARCHAR2(3), 
	"LOGON_NUMBER" NUMBER(3,0) NOT NULL ENABLE, 
	"PROJECT_PASSWORD" VARCHAR2(255), 
	"PWD_MOD_DATE" DATE, 
	"LOGON_ERROR_NUMBER" NUMBER(3,0), 
	"LDAP_ID" VARCHAR2(255), 
	"PHS_TEL" VARCHAR2(20), 
	"HIS_PWD" VARCHAR2(256), 
	"LOCKED_DATE" DATE, 
	"CERT_NO" VARCHAR2(100), 
	"RELA_TYPE" VARCHAR2(100), 
	"PWD_QUESTION" VARCHAR2(4000), 
	"PWD_ANSWER" VARCHAR2(4000), 
	"ISSETANDMAINTAIN" VARCHAR2(100), 
	"PRO_ATTRIBUTE" VARCHAR2(20) DEFAULT 'AB', 
	"AREA_ATTRIBUTE" VARCHAR2(20), 
	"ZJ_LIMIT" NUMBER(6,0), 
	"TS_LIMIT" NUMBER(6,0), 
	"PRIORITY_LEVEL" VARCHAR2(20), 
	"WEAK_LIGHT_LIMIT" NUMBER(6,0) DEFAULT 4, 
	"ZJ_TS_LIMIT" NUMBER(3,0), 
	"TS_ZJ_LIMIT" NUMBER(3,0), 
	"RES_ORDER_LIMIT" NUMBER(6,0) DEFAULT 0, 
	"BUSINESS_EXPRESS_LIMIT" NUMBER(6,0) DEFAULT 5, 
	"GIGA_ORDER_LIMIT" NUMBER(6,0) DEFAULT 10, 
	"CHG_ZNWG_LIMIT" NUMBER(6,0) DEFAULT 10, 
	"POSITION" VARCHAR2(100), 
	"GIGA_BIT_VIP_ORDER_LIMIT" NUMBER(6,0) DEFAULT 10, 
	 CONSTRAINT "PK_UOS_STAFF_IOM11" PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 8192 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."PRO_ATTRIBUTE" IS '专职属性（A:装 B：维 AB:装维）default值AB';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."AREA_ATTRIBUTE" IS '区域属性（T:城镇  C:农村）';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."ZJ_LIMIT" IS '装机阈值';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."TS_LIMIT" IS '投诉阈值';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."PRIORITY_LEVEL" IS '优先级 A-高 B-中 C-低';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."ZJ_TS_LIMIT" IS '投诉装机阈值';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."TS_ZJ_LIMIT" IS '装机投诉阈值';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."RES_ORDER_LIMIT" IS '未覆盖预受理工单的阀值';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."BUSINESS_EXPRESS_LIMIT" IS '商务快线阈值';
 
   COMMENT ON COLUMN "YDZC"."UOS_STAFF_IOM"."GIGA_ORDER_LIMIT" IS '千兆阀值';
 

  CREATE INDEX "YDZC"."IDX_UOS_STAFF_IOM_STATE11" ON "YDZC"."UOS_STAFF_IOM" ("STATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE INDEX "YDZC"."IDX_UOS_STAFF_IOM_USERNAME11" ON "YDZC"."UOS_STAFF_IOM" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
  CREATE TABLE "YDZC"."UOS_ORG_IOM" 
   (	ORG_ID NUMBER(9,0) NOT NULL ENABLE, 
	ORG_TMP_ID NUMBER(8,0) NOT NULL ENABLE, 
	AREA_ID NUMBER(9,0) NOT NULL ENABLE, 
	ORG_NAME VARCHAR2(64) NOT NULL ENABLE, 
	PARENT_ID NUMBER(10,0), 
	ORG_PATH_NAME VARCHAR2(512) NOT NULL ENABLE, 
	ORG_PATH_CODE VARCHAR2(254) NOT NULL ENABLE, 
	ACRONYM VARCHAR2(64), 
	ALIAS VARCHAR2(64), 
	TEL VARCHAR2(20), 
	FAX VARCHAR2(20), 
	EFFECT_DATE DATE, 
	EXPIRE_DATE DATE, 
	UPDATE_DATE DATE DEFAULT sysdate, 
	STATE CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	COMMENTS VARCHAR2(255), 
	DISPLAY_INDEX VARCHAR2(254), 
	ORG_CODE VARCHAR2(64), 
	LDAP_ID VARCHAR2(255), 
	ORG_TYPE_ID VARCHAR2(3), 
	EMAIL VARCHAR2(60), 
	ODSO_ORG_ID NUMBER(12,0), 
	ODSO_ORG_CODE VARCHAR2(16), 
	ODSO_OPE_FLAG VARCHAR2(2), 
	DEAL_RESULT VARCHAR2(2), 
	IS_DW NUMBER(3,0), 
	DW_PATH_CODE VARCHAR2(64), 
	DW_PID NUMBER(9,0), 
	DAIWEI_COMPANY_ID VARCHAR2(20),
	UPDATE_TIME DATE NOT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  
  CREATE TABLE "YDZC"."UOS_JOB_IOM" 
   (	JOB_ID NUMBER(9,0) NOT NULL ENABLE, 
	ORG_ID NUMBER(9,0) NOT NULL ENABLE, 
	POST_ID NUMBER(9,0), 
	JOB_NAME VARCHAR2(60) NOT NULL ENABLE, 
	STATE CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	COMMENTS VARCHAR2(255), 
	LDAP_ID VARCHAR2(255), 
	UPDATE_DATE DATE, 
	EMAIL VARCHAR2(60),
  	UPDATE_TIME DATE NOT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  CREATE TABLE "YDZC"."UOS_JOB_PRIV_IOM" 
   (	JOB_PRIV_ID NUMBER, 
	ROLE_ID NUMBER, 
	PRIV_CODE VARCHAR2(255), 
	JOB_ID NUMBER, 
	EFFECT_DATE DATE, 
	EXPIRE_DATE DATE, 
	UPDATE_DATE DATE, 
	CAN_GRANT VARCHAR2(255),
  	UPDATE_TIME DATE DEFAULT sysdate,
	DATA_SOURCE NUMBER default 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;
  
CREATE SEQUENCE UOS_JOB_PRIV_IOM_SEQ
START WITH 999999
INCREMENT BY -1
MINVALUE 100000
MAXVALUE 1000000
CACHE 10
NOCYCLE;
  

create table "YDZC".UOS_ROLE_IOM
(
  ROLE_ID   NUMBER(8) not null,
  ROLE_NAME VARCHAR2(60) not null,
  COMMENTS  VARCHAR2(255),
  AREA_ID   NUMBER(9),
  UPDATE_TIME DATE NOT NULL,
 constraint PK_UOS_ROLE primary key (ROLE_ID)
) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645)
  TABLESPACE "USERS" ;

CREATE TABLE "YDZC"."UOS_JOB_STAFF_IOM" 
   (	"JOB_STAFF_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"JOB_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STATE" CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	"IS_NORMAL" CHAR(1) DEFAULT '1' NOT NULL ENABLE, 
	"ISBASIC" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"STAFF_ID" NUMBER(8,0) NOT NULL ENABLE,
  	UPDATE_TIME DATE NOT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";